export const GET_ROVER_IMAGES = "GET_ROVER_IMAGES"
export const GET_ROVER_IMAGES_ERROR = "GET_ROVER_IMAGES_ERROR"

export const GET_SPIRIT_IMAGES_SUCCESS = "GET_SPIRIT_IMAGES_SUCCESS"
export const SET_DATE_SPIRIT = "SET_DATE_SPIRIT"

export const GET_CURIOSITY_IMAGES_SUCCESS = "GET_CURIOSITY_IMAGES_SUCCESS"
export const SET_DATE_CURIOSITY = "SET_DATE_CURIOSITY"

export const GET_OPPORTUNITY_IMAGES_SUCCESS = "GET_OPPORTUNITY_IMAGES_SUCCESS"
export const SET_DATE_OPPORTUNITY = "SET_DATE_OPPORTUNITY"
export const LOADING = "LOADING"